Make work with collections
yanneves/metalsmith-metadata-in-filename pull request #1
Opened 2017-05-10 14:19 UTC by runemadsen

This PR fixes two things:

- It removes the folder names from filenames so dates and slugs can be parsed from collection pages
- If we can't parse the date in a filename, it'll not assign the metadata

2017-05-11 09:45 UTC, yanneves commented
Thanks for the PR @runemadsen! 💯 

Could I ask you to add two test cases, one for each of those changes?
Otherwise looks great, I'll merge and publish a new version once that's done.

2017-05-11 15:26 UTC, runemadsen commented
Done!

2017-05-11 16:02 UTC, yanneves requested changes
Nice, thanks, only some minor changes here

2017-05-11 16:02 UTC, yanneves commented on test/index.js
> +      let filename = 'no-date.md'
should be defined as `const`

2017-05-11 16:02 UTC, yanneves commented on test/index.js
> +      let title = 'no-date'
should be defined as `const`

2017-05-11 16:02 UTC, yanneves commented on test/index.js
> +          expect(files[filename].slug).to.equal('no-date')
should use `title` defined above instead of hard-coded `'no-date'`

2017-05-12 08:30 UTC, runemadsen commented
Done!

2017-05-12 08:48 UTC, yanneves approved these changes

2017-05-12 08:48 UTC, merged